### ISSUE TITLE
Live preview: where?

### ISSUE THREAD

**Issue by jsonin** [goinvo/DigitalHealthServiceComponents#1]
@ericbenwa should we use netlify or?
any suggestions (@poofytoo may have ideas)...

**Comment by poofytoo** [comment]
I've hoofed it onto GitHub's minimal built-in hosting service: Github Pages [https://goinvo.github.io/DigitalHealthServiceComponents](https://goinvo.github.io/DigitalHealthServiceComponents)/ for now. That process isn't the best (need to run a specific command: `git subtree push --prefix web origin gh-pages`)... so netlify may be a better option

Right now, focusing on the 'scroll' behavior. The scroll is true to the body of text on the right, and the diagram on the left follows it proportionally (and, as expected, nothing lines up correctly)

Thinking of switching it around so that the scroll is true to the left, and then the text shifts around on the right as certain layers on the left come into view. Will also adjust speed to match it so that the text actually shows up beside the relevant shown layer.

Will also make it so that clicking a specific layer jumps to a section, etc.

**Comment by jsonin** [comment]
Good call to use github.io.

And solid v.001.
It's forcing me to write more today/tomorrow, to fill out the content... which will also allow for better scroll testing.

Mobile is going to be a PIA... unless we're shoving the text _under_ each layer (vs on the right side, where the accompanying text is now).

**Comment by poofytoo** [comment]
For mobile, was thinking of keeping text hidden until the layer is tapped, and only then does it expand under each layer. What do you think about that?

**Comment by jsonin** [comment]
That works. Thx.

**Comment by poofytoo** [comment]
Didn't get an interaction I quite liked on desktop, so took a stab at mobile. All I did was squeeze things around to make it fit (just the stack, not the text yet). Plan to implement this quick mock: https://www.figma.com/file/9CFtzTP0IHgIvG67NoOVkL/Health-IT-Digital-Service-Components?node-id=803%3A218 for the text that shows up when something is clicked.

**Comment by jsonin** [comment]
✔️

**Comment by jsonin** [comment]
I can start putting in realer and realer content into the descriptions + actual layer config.

LMK when that's ok, and I'll start updating the content.

**Comment by poofytoo** [comment]
Yep! You can add content. If you're ok adding things to this file: https://github.com/goinvo/DigitalHealthServiceComponents/blob/main/web/src/data/content.jsx you can go ahead and add things there.

**Comment by poofytoo** [comment]
(Let me know if not or if that file is too hairy for your likings, I can think about some better formatting. It's in a pretty raw .json content format right now)
